"""Report generation — Markdown and HTML reports for benchmark results."""

from datetime import datetime, timezone
from html import escape
from pathlib import Path

from mojomark.compare import BenchmarkDiff, Status, summarize_diffs

REPORTS_DIR = Path(__file__).parent.parent.parent / "reports"


def format_time(ns: float) -> str:
    """Format nanoseconds into a human-readable string."""
    if ns < 1_000:
        return f"{ns:.0f} ns"
    elif ns < 1_000_000:
        return f"{ns / 1_000:.1f} us"
    elif ns < 1_000_000_000:
        return f"{ns / 1_000_000:.1f} ms"
    else:
        return f"{ns / 1_000_000_000:.2f} s"


def _status_emoji(status: Status) -> str:
    """Map status to a plain-text indicator for Markdown."""
    return {
        Status.IMPROVED: ">> improved",
        Status.STABLE: "OK stable",
        Status.WARNING: "!! warning",
        Status.REGRESSION: "XX REGRESSION",
    }[status]


def _status_html_badge(status: Status) -> str:
    """Map status to a colored HTML badge."""
    colors = {
        Status.IMPROVED: ("#065f46", "#d1fae5"),
        Status.STABLE: ("#166534", "#dcfce7"),
        Status.WARNING: ("#854d0e", "#fef9c3"),
        Status.REGRESSION: ("#991b1b", "#fee2e2"),
    }
    labels = {
        Status.IMPROVED: ">> improved",
        Status.STABLE: "OK stable",
        Status.WARNING: "!! warning",
        Status.REGRESSION: "XX REGRESSION",
    }
    fg, bg = colors[status]
    return (
        f'<span style="background:{bg};color:{fg};padding:2px 8px;'
        f'border-radius:4px;font-weight:600;font-size:0.85em">'
        f"{labels[status]}</span>"
    )


# ---------------------------------------------------------------------------
# Markdown generation
# ---------------------------------------------------------------------------


def generate_single_run_markdown(result_data: dict) -> str:
    """Generate a Markdown report for a single benchmark run.

    Args:
        result_data: Parsed JSON result data from a benchmark run.

    Returns:
        Markdown string.
    """
    version = result_data["mojo_version"]
    timestamp = result_data["timestamp"][:19].replace("T", " ")
    benchmarks = result_data["benchmarks"]

    lines: list[str] = []
    lines.append(f"# mojomark Report — Mojo {version}")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"**Mojo version:** {version}")
    lines.append(f"**Run timestamp:** {timestamp}")
    lines.append(f"**Benchmarks:** {len(benchmarks)}")
    lines.append("")

    lines.append("## Results")
    lines.append("")
    lines.append("| Category | Benchmark | Mean | Median | Min | Max | Std Dev | Samples |")
    lines.append("|----------|-----------|-----:|-------:|----:|----:|--------:|--------:|")

    for b in benchmarks:
        stats = b["stats"]
        lines.append(
            f"| {b['category']} "
            f"| {b['name']} "
            f"| {format_time(stats['mean_ns'])} "
            f"| {format_time(stats['median_ns'])} "
            f"| {format_time(stats['min_ns'])} "
            f"| {format_time(stats['max_ns'])} "
            f"| {format_time(stats['std_dev_ns'])} "
            f"| {stats['samples']} |"
        )

    lines.append("")
    lines.append("---")
    lines.append("*Generated by [mojomark](https://github.com/mojomark)*")
    lines.append("")
    return "\n".join(lines)


def generate_comparison_markdown(
    base_data: dict,
    target_data: dict,
    diffs: list[BenchmarkDiff],
) -> str:
    """Generate a Markdown report comparing two Mojo versions.

    Args:
        base_data: Baseline result data.
        target_data: Target result data.
        diffs: Pre-computed benchmark diffs.

    Returns:
        Markdown string.
    """
    base_ver = base_data["mojo_version"]
    target_ver = target_data["mojo_version"]

    lines: list[str] = []
    lines.append(f"# mojomark Comparison — Mojo {base_ver} vs {target_ver}")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"**Base version:** {base_ver}")
    lines.append(f"**Target version:** {target_ver}")
    lines.append("")

    summary = summarize_diffs(diffs)
    summary_parts = []
    if summary[Status.IMPROVED]:
        summary_parts.append(f"**{summary[Status.IMPROVED]}** improved")
    if summary[Status.STABLE]:
        summary_parts.append(f"**{summary[Status.STABLE]}** stable")
    if summary[Status.WARNING]:
        summary_parts.append(f"**{summary[Status.WARNING]}** warning")
    if summary[Status.REGRESSION]:
        summary_parts.append(f"**{summary[Status.REGRESSION]}** regression")

    lines.append("## Summary")
    lines.append("")
    lines.append(" | ".join(summary_parts))
    lines.append("")

    lines.append("## Benchmark Comparison")
    lines.append("")
    lines.append(f"| Category | Benchmark | {base_ver} | {target_ver} | Delta | Status |")
    lines.append("|----------|-----------|-------:|-------:|------:|--------|")

    for d in diffs:
        lines.append(
            f"| {d.category} "
            f"| {d.name} "
            f"| {format_time(d.base_mean_ns)} "
            f"| {format_time(d.target_mean_ns)} "
            f"| {d.delta_pct:+.1f}% "
            f"| {_status_emoji(d.status)} |"
        )

    lines.append("")

    lines.append("### Thresholds")
    lines.append("")
    lines.append("| Indicator | Meaning |")
    lines.append("|-----------|---------|")
    lines.append("| `>>` improved | > 5% faster |")
    lines.append("| `OK` stable | < 3% change |")
    lines.append("| `!!` warning | 3–10% slower |")
    lines.append("| `XX` REGRESSION | > 10% slower |")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by [mojomark](https://github.com/mojomark)*")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML generation
# ---------------------------------------------------------------------------

_HTML_TEMPLATE_HEAD = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  :root {{
    --bg: #0f172a;
    --surface: #1e293b;
    --border: #334155;
    --text: #e2e8f0;
    --text-dim: #94a3b8;
    --accent: #38bdf8;
    --green: #4ade80;
    --red: #f87171;
    --yellow: #facc15;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: 'SF Mono', 'Fira Code', 'Cascadia Code', monospace;
    background: var(--bg);
    color: var(--text);
    padding: 2rem;
    max-width: 1100px;
    margin: 0 auto;
    line-height: 1.6;
  }}
  h1 {{
    color: var(--accent);
    font-size: 1.5rem;
    margin-bottom: 0.25rem;
  }}
  h2 {{
    color: var(--text);
    font-size: 1.15rem;
    margin-top: 2rem;
    margin-bottom: 0.75rem;
    border-bottom: 1px solid var(--border);
    padding-bottom: 0.4rem;
  }}
  .meta {{
    color: var(--text-dim);
    font-size: 0.85rem;
    margin-bottom: 1.5rem;
  }}
  .meta span {{
    margin-right: 1.5rem;
  }}
  .summary {{
    display: flex;
    gap: 1rem;
    flex-wrap: wrap;
    margin-bottom: 1.5rem;
  }}
  .summary-card {{
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 0.75rem 1.25rem;
    text-align: center;
  }}
  .summary-card .count {{
    font-size: 1.5rem;
    font-weight: 700;
  }}
  .summary-card .label {{
    font-size: 0.8rem;
    color: var(--text-dim);
    text-transform: uppercase;
  }}
  table {{
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 1.5rem;
    font-size: 0.9rem;
  }}
  th {{
    background: var(--surface);
    color: var(--accent);
    text-align: left;
    padding: 0.6rem 0.75rem;
    border-bottom: 2px solid var(--border);
    font-weight: 600;
  }}
  th.right {{ text-align: right; }}
  td {{
    padding: 0.5rem 0.75rem;
    border-bottom: 1px solid var(--border);
  }}
  td.right {{ text-align: right; font-variant-numeric: tabular-nums; }}
  tr:hover td {{ background: rgba(56, 189, 248, 0.05); }}
  .delta-positive {{ color: var(--red); }}
  .delta-negative {{ color: var(--green); }}
  .delta-neutral {{ color: var(--text-dim); }}
  footer {{
    margin-top: 3rem;
    padding-top: 1rem;
    border-top: 1px solid var(--border);
    color: var(--text-dim);
    font-size: 0.8rem;
  }}
</style>
</head>
<body>
"""

_HTML_TEMPLATE_FOOT = """\
<footer>
  Generated by mojomark &mdash; Mojo Performance Regression Detector
</footer>
</body>
</html>
"""


def generate_single_run_html(result_data: dict) -> str:
    """Generate a self-contained HTML report for a single benchmark run.

    Args:
        result_data: Parsed JSON result data from a benchmark run.

    Returns:
        HTML string.
    """
    version = result_data["mojo_version"]
    timestamp = result_data["timestamp"][:19].replace("T", " ")
    benchmarks = result_data["benchmarks"]

    parts: list[str] = []
    parts.append(_HTML_TEMPLATE_HEAD.format(title=f"mojomark — Mojo {version}"))

    parts.append("<h1>mojomark Report</h1>")
    parts.append(
        f'<div class="meta">'
        f"<span>Mojo {escape(version)}</span>"
        f"<span>{escape(timestamp)}</span>"
        f"<span>{len(benchmarks)} benchmarks</span>"
        f"</div>"
    )

    categories = set(b["category"] for b in benchmarks)
    parts.append('<div class="summary">')
    parts.append(
        f'<div class="summary-card">'
        f'<div class="count">{len(benchmarks)}</div>'
        f'<div class="label">Benchmarks</div></div>'
    )
    parts.append(
        f'<div class="summary-card">'
        f'<div class="count">{len(categories)}</div>'
        f'<div class="label">Categories</div></div>'
    )
    if benchmarks:
        total_samples = sum(b["stats"]["samples"] for b in benchmarks)
        parts.append(
            f'<div class="summary-card">'
            f'<div class="count">{total_samples}</div>'
            f'<div class="label">Total Samples</div></div>'
        )
    parts.append("</div>")

    parts.append("<h2>Results</h2>")
    parts.append("<table>")
    parts.append(
        "<thead><tr>"
        "<th>Category</th><th>Benchmark</th>"
        '<th class="right">Mean</th><th class="right">Median</th>'
        '<th class="right">Min</th><th class="right">Max</th>'
        '<th class="right">Std Dev</th><th class="right">Samples</th>'
        "</tr></thead>"
    )
    parts.append("<tbody>")

    for b in benchmarks:
        s = b["stats"]
        parts.append(
            f"<tr>"
            f"<td>{escape(b['category'])}</td><td>{escape(b['name'])}</td>"
            f'<td class="right">{format_time(s["mean_ns"])}</td>'
            f'<td class="right">{format_time(s["median_ns"])}</td>'
            f'<td class="right">{format_time(s["min_ns"])}</td>'
            f'<td class="right">{format_time(s["max_ns"])}</td>'
            f'<td class="right">{format_time(s["std_dev_ns"])}</td>'
            f'<td class="right">{s["samples"]}</td>'
            f"</tr>"
        )

    parts.append("</tbody>")
    parts.append("</table>")
    parts.append(_HTML_TEMPLATE_FOOT)
    return "\n".join(parts)


def generate_comparison_html(
    base_data: dict,
    target_data: dict,
    diffs: list[BenchmarkDiff],
) -> str:
    """Generate a self-contained HTML report comparing two Mojo versions.

    Args:
        base_data: Baseline result data.
        target_data: Target result data.
        diffs: Pre-computed benchmark diffs.

    Returns:
        HTML string.
    """
    base_ver = base_data["mojo_version"]
    target_ver = target_data["mojo_version"]
    summary = summarize_diffs(diffs)

    parts: list[str] = []
    parts.append(_HTML_TEMPLATE_HEAD.format(title=f"mojomark — {base_ver} vs {target_ver}"))

    parts.append("<h1>mojomark Comparison</h1>")
    parts.append(
        f'<div class="meta">'
        f"<span>Mojo {escape(base_ver)} &rarr; {escape(target_ver)}</span>"
        f"<span>{len(diffs)} benchmarks compared</span>"
        f"</div>"
    )

    parts.append('<div class="summary">')
    card_data = [
        (summary[Status.IMPROVED], "Improved", "var(--green)"),
        (summary[Status.STABLE], "Stable", "var(--text)"),
        (summary[Status.WARNING], "Warning", "var(--yellow)"),
        (summary[Status.REGRESSION], "Regression", "var(--red)"),
    ]
    for count, label, color in card_data:
        parts.append(
            f'<div class="summary-card">'
            f'<div class="count" style="color:{color}">{count}</div>'
            f'<div class="label">{label}</div></div>'
        )
    parts.append("</div>")

    parts.append("<h2>Benchmark Comparison</h2>")
    parts.append("<table>")
    parts.append(
        f"<thead><tr>"
        f"<th>Category</th><th>Benchmark</th>"
        f'<th class="right">{escape(base_ver)}</th>'
        f'<th class="right">{escape(target_ver)}</th>'
        f'<th class="right">Delta</th>'
        f"<th>Status</th>"
        f"</tr></thead>"
    )
    parts.append("<tbody>")

    for d in diffs:
        if d.delta_pct >= 3:
            delta_class = "delta-positive"
        elif d.delta_pct <= -5:
            delta_class = "delta-negative"
        else:
            delta_class = "delta-neutral"

        parts.append(
            f"<tr>"
            f"<td>{escape(d.category)}</td><td>{escape(d.name)}</td>"
            f'<td class="right">{format_time(d.base_mean_ns)}</td>'
            f'<td class="right">{format_time(d.target_mean_ns)}</td>'
            f'<td class="right {delta_class}">{d.delta_pct:+.1f}%</td>'
            f"<td>{_status_html_badge(d.status)}</td>"
            f"</tr>"
        )

    parts.append("</tbody>")
    parts.append("</table>")
    parts.append(_HTML_TEMPLATE_FOOT)
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# File saving
# ---------------------------------------------------------------------------


def save_report(
    content: str,
    filename: str,
    reports_dir: Path = REPORTS_DIR,
) -> Path:
    """Save report content to the reports directory.

    Args:
        content: Report content (Markdown or HTML).
        filename: Output filename.
        reports_dir: Directory to save reports in.

    Returns:
        Path to the saved report file.
    """
    reports_dir.mkdir(parents=True, exist_ok=True)
    filepath = reports_dir / filename
    filepath.write_text(content)
    return filepath
